MODEL:
  NUM_CLASSES: 5
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 107, 160, 320]
    MIN_SIZES: [60, 105, 150, 195, 240, 285]
    MAX_SIZES: [105, 150, 195, 240, 285, 330]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("my_custom_trainval", )
  TEST: ("my_custom_test", )
SOLVER:
  MAX_ITER: 72000
  LR_STEPS: [48000, 60000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-4
TEST:
  NMS_THRESHOLD: 0.5
  CONFIDENCE_THRESHOLD: 0.3

OUTPUT_DIR: '/content/drive/MyDrive/Colab Notebooks/Sunshine Tech/models/mobilenetv2_ssd320_my_dataset'